package com.manav.drools.rules;
import  com.manav.drools.entity.OrderRequest;
rule "Discount for CARD payment above 10000"
    when
        OrderRequest( tp:totalPrice);
        orderObject : OrderRequest( paymentType=="CARD" && totalPrice >= 10000);
    then
        orderObject.setDiscount(15);
        orderObject.setDiscountedPrice(tp*(1-0.15));
end;
rule "Discount for CARD payment below 10000"
    when
        OrderRequest( tp:totalPrice);
        orderObject : OrderRequest( paymentType=="CARD" && totalPrice >= 5000 && totalPrice < 10000);
    then
        orderObject.setDiscount(5);
        orderObject.setDiscountedPrice(tp*(1-0.05));
end;
rule "No Discount for CARD payment below 5000"
    when
        OrderRequest( tp:totalPrice);
        orderObject : OrderRequest( paymentType=="CARD" && totalPrice < 5000);
    then
        orderObject.setDiscount(0);
        orderObject.setDiscountedPrice(tp);
end;